log:
  level: DEBUG

api:
  debug: true
  insecure: true

entryPoints:
  web:
    address: :80

providers:
  docker:
    swarmMode: true
    watch: true
    network: domain_world
    exposedbydefault: false
    endpoint: unix://var/run/docker.sock
